# Generated by Django 2.2.7 on 2019-12-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shuffeled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('circulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulo.Circulo')),
            ],
        ),
        migrations.CreateModel(
            name='Deseo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deseo', models.CharField(max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='circulo.Persona')),
            ],
        ),
    ]
