# Generated by Django 2.2.7 on 2019-12-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='circulo',
            name='nombre',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
