# Generated by Django 2.2.7 on 2019-12-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulo', '0002_circulo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
