# Generated by Django 2.2.7 on 2019-12-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circulo', '0004_auto_20191202_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circulo',
            name='shuffeled',
            field=models.BooleanField(default=False),
        ),
    ]
